# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Duck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=255)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
